### PR TITLE
generate css with travis

### PR DESCRIPTION
**Pull request by DO1JLR**
Eventually this could work. We will see...

The script from @ottojo probably won't generate css.

### CODE REVIEW

**Comment by DO1JLR** [comment]
Issue #220

**Comment by maxbachmann** [comment]
Genau die Funktion habe ich auch schon gesucht :+1: 
Also die um zu checken ob eine Datei existiert :)

**Comment by maxbachmann** [comment]
ah already though the lektor clear is wrong :)

**Comment by DO1JLR** [comment]
> ah already though the lektor clear is wrong :)

Should be fixed with https://github.com/ToolboxBodensee/toolbox-webseite/pull/229/commits/9cf1b86cb34caaf6277d3f13bd44d88266a49889, we will see what travis will say!

**Comment by DO1JLR** [comment]
> I already searched the function to check if a file exists locally but could not find it glad you found one :)

I am happy about this too. ``|asseturl `` only work in the asset/ folder. But I think this is a great start!

**Comment by maxbachmann** [comment]
well we only need to check for assets anyways

**Pull request merged**
