### PR TITLE
Fix pullrequest deployment script

### PR DESCRIPTION
**Pull request by ottojo**
Does not build again on staging server, travis build gets uploaded.
Should reduce travis build time by 50%

Staging server config: https://github.com/ToolboxBodensee/stagingServerConfig

### CODE REVIEW

**Comment by maxbachmann** [comment]
appears like you forgot a --yes somewhere in your ssh stuff

**Comment by ottojo** [comment]
View this PR on https://302.tbp.ottojo.space

**Comment by ottojo** [comment]
TODO: LFS Pointers are currently not converted to files, because the environment variable GIT_LFS_SKIP_SMUDGE is set to 1, we should get LFS assets after successful build.

**Comment by maxbachmann** [comment]
does it build the assets now aswell?

**Pull request merged**
